### ISSUE TITLE
Tracking issue for better Starrocks compatibility

### ISSUE THREAD

**Issue by c-thiel** [hansetag/iceberg-catalog#316]
- [x] Configurable OAuth Endpoint https://github.com/StarRocks/starrocks/issues/50112
- [x] Support no credentials https://github.com/StarRocks/starrocks/issues/50518
- [ ] https://github.com/StarRocks/starrocks/issues/50585

**Comment by c-thiel** [comment]
Closed in favor of https://github.com/hansetag/iceberg-catalog/issues/399
