### ISSUE TITLE
Tracking: Better Query Engine compatibility (Spark, Trino, Starrocks, Presto)

### ISSUE THREAD

**Issue by c-thiel** [hansetag/iceberg-catalog#399]
Spark:
- [ ] Remove orphan files with vended credentials (https://github.com/apache/iceberg/pull/7914)

Trino:
- [ ] Vended creds for Azure (https://github.com/trinodb/trino/issues/23238)
- [ ] Remote signing S3: (https://github.com/trinodb/trino/issues/21189)
- [ ] AuthN: Specify token endpoint (https://github.com/trinodb/trino/issues/23086)

Starrocks:
- [ ] Remote signing S3: https://github.com/StarRocks/starrocks/issues/50585

Presto:
- [x] Configurable OAauth Endpoint (https://github.com/prestodb/presto/issues/23491)

**Comment by vkingnew** [comment]
apache doris Integrated  required
